/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eleicoes;

import eleicoes.Atributos.Candidato;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class VotarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VotarUsuario
     */
    public VotarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonConfirmar = new javax.swing.JButton();
        buttonDados = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        comboCandidato = new javax.swing.JComboBox<>();
        labelText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonConfirmar.setText("Confirmar voto");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        buttonDados.setText("Mostrar dados");
        buttonDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDadosActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        labelText.setText("Selecione o candidato que deseja voltar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelText)
                    .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmar)
                    .addComponent(buttonDados)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(int i=0 ; i<Eleicoes.currentElection.getNumCandidato().size() ; i++){
            comboCandidato.addItem(Eleicoes.currentElection.getNumCandidato().get(i).toString());
        }
    }//GEN-LAST:event_formWindowOpened

    private void buttonDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDadosActionPerformed
        if(comboCandidato.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Sem candidatos registrados!");
        }else{
            Candidato c = Eleicoes.gc.consultarNumero(Integer.parseInt(comboCandidato.getSelectedItem().toString()));
            JOptionPane.showMessageDialog(this, c.toString());
        }
    }//GEN-LAST:event_buttonDadosActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        if(comboCandidato.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Sem candidatos registrados.");
        }else{
            boolean votou = false;
            //Testa se o Eleitor logado já votou nesta eleição
            for(int i=0 ; i<Eleicoes.currentElection.getCpfVotantes().size() ; i++){
                if(Eleicoes.currentElection.getCpfVotantes().get(i).equals(Eleicoes.loggedUser.getCpf())){
                    JOptionPane.showMessageDialog(this, "Você já votou nesta eleição");
                    votou = true;
                    dispose();
                }
            }
            //Adiciona 1 na variável de votos referente ao candidato selecionado e adiciona o cpf do eleitor na lista 
            //dos eleitores que já votaram na eleição
            if(votou == false){
                try{
                    ArrayList a = Eleicoes.currentElection.getNumCandidato();
                    for (int i=0 ; i<a.size() ; i++){
                        if(Integer.parseInt(comboCandidato.getSelectedItem().toString()) == Integer.parseInt(a.get(i).toString())){
                            Eleicoes.currentElection.setVotosCandidato(i, Integer.parseInt(Eleicoes.currentElection.getVotosCandidato().get(i).toString())+1);
                        }
                    }
                    Eleicoes.currentElection.addCpfVotante(Eleicoes.geleitor.consutaCpfPorUsuario(Eleicoes.loggedUser.getNomeUser()));
                    JOptionPane.showMessageDialog(this, "Voto computado: \n"+Eleicoes.gc.consultarNumero(Integer.parseInt(comboCandidato.getSelectedItem().toString())));
                    for(int i=0 ; i<Eleicoes.geleicao.listEleicao.size() ; i++){
                        Eleicoes.exportCSVEleicaoCpf(i);
                        Eleicoes.exportCSVEleicaoCand(i);
                        Eleicoes.exportCSVEleicaoVotos(i);
                    }
                    dispose();
                }catch(Exception e){
                    System.err.println("Erro: "+e);
                }
            }
        }
        
        
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonDados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCandidato;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables
}
